export const GOOGLE_API_KEY: string = 'AIzaSyCOLDSLmmBjEDIlOmzHOEoAakcZQRlp31Y'
export const GOOGLE_CLIENT_ID: string = '352226282642-jokokdl4q6ccrhrfgbhgj6pb4jqupo54.apps.googleusercontent.com'
export const GOOGLE_SECRET_KEY: string = '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'
export const API_BASE_URL: string = 'https://unetwork-api.onrender.com/' 
export const REDUX_PERSIST_STORE_KEY = ')7#o6ub43kJ1@8phr2kuICLYI75s4/£[5NeHxbBe"~N;Q(GDZv'