import DiscoverSection from './Home/DiscoverSection'
import ForumSection from './Home/ForumSection'
import ComunitySection from './Home/ComunitySection'
import Chat from './Chat/Chat'
import Notice from './News/LittleNotice'
import SideBar from './SideBar/SideBar'
import Folder from './Materials/Folder'
import File from './Materials/File'
import Contact from './Chat/Contact'
import Classes from './Classes/Classes'
export { DiscoverSection, ForumSection, ComunitySection, Chat, Notice, SideBar, Folder, File, Contact, Classes}
